apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis
  namespace: {{ .Values.ocpProjectName }}
spec:
  podSelector:
    matchLabels:
      networkPolicy: redis
      app.kubernetes.io/name: prometheus
  ingress:
    - ports:
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 26379
        - protocol: TCP
          port: 9121
      from:
        - podSelector: {}
  policyTypes:
    - Ingress
