apiVersion: v1
kind: Service
metadata:
  name: redis-1
  labels:
    app: redis-1
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-1
    - port: 26379
      targetPort: 26379
      name: sentinel-1
    - port: 9121
      name: metrics-1
      protocol: TCP
      targetPort: 9121
  selector:
    app: redis-1
  {{ if .Values.needLoadbalancer }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadbalancerIP1 }}
  {{ end }}
