apiVersion: v1
kind: Service
metadata:
  name: redis-0
  labels:
    app: redis-0
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-0
    - port: 26379
      targetPort: 26379
      name: sentinel-0
    - port: 9121
      name: metrics-0
      protocol: TCP
      targetPort: 9121
  selector:
    app: redis-0
  {{ if .Values.needLoadbalancer }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadbalancerIP0 }}
  {{ end }}
