apiVersion: v1
kind: Service
metadata:
  name: redis-2
  labels:
    app: redis-2
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-2
    - port: 26379
      targetPort: 26379
      name: sentinel-2
    - port: 9121
      name: metrics-2
      protocol: TCP
      targetPort: 9121
  selector:
    app: redis-2
  {{ if .Values.needLoadbalancer }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadbalancerIP2 }}
  {{ end }}
