apiVersion: v1
kind: Service
metadata:
  name: redis-2
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-2
    - port: 26379
      targetPort: 26379
      name: sentinel-2
  selector:
    app: redis-2
  {{ if eq .Values.containerPlatform "anthos" }}
  type: LoadBalancer
  loadBalancerIP: 10.230.249.134
  {{ end }}
