apiVersion: v1
kind: Service
metadata:
  name: redis-0
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-0
    - port: 26379
      targetPort: 26379
      name: sentinel-0
  selector:
    app: redis-0
  {{ if eq .Values.containerPlatform "anthos" }}
  type: LoadBalancer
  loadBalancerIP: 10.230.249.132
  {{ end }}
